import java.util.ArrayList;

public class ComputerPlayer implements Player{

    private ArrayList<Integer> playerRowsNumbers;       //rows of player
    private ArrayList<Dice> playerDices = new ArrayList<>();    //dice of player
    private String playerName;
    private Strategy strategy = new Strategy();


    public ComputerPlayer(String name){
        try {
            this.playerName = name;
            createDices();
        }catch (Exception e){
            System.out.println(e.toString());
        }
    }

    //create 4 dice
    private void createDices(){
        int index ;
        for (index=0 ; index<4 ; index++){
            playerDices.add(new Dice());
        }
    }

    //each round player makes move
    @Override
    public Move makeMove() {
        ArrayList<Integer> strategyRows = new ArrayList<>();    //rows of player will select
        rollDice();
        System.out.print("Your dices are :");
        playerDices.forEach((dice) -> System.out.print(dice.getRandomInt() + " "));
        System.out.println();
        //to select rows computer generate strategy
        strategyRows = strategy.generateStrategy(playerDices,playerRowsNumbers);

        //make move according to rows which generated by strategy
        if(strategyRows.size() == 2) {
            return new Move(strategyRows.get(0),strategyRows.get(1));
        }else if(strategyRows.size() == 1) {
            return new Move(strategyRows.get(0));
        }else {
            return new Move();
        }
    }

    //return dice number
    public ArrayList<Dice> getDiceNumbers(){
        return playerDices;
    }

    //players selected rows which select first round
    public ArrayList<Integer> getPlayerRowsNumbers(){
        return playerRowsNumbers;
    }

    //select rows in first round which is selection round
    public ArrayList<Integer> selectPlayerRows(){
        ArrayList<Integer> selectedRows = new ArrayList<>();
        selectedRows = strategy.selectRows(playerDices); // select rows according to strategy
        playerRowsNumbers = selectedRows;
        return selectedRows;
    }

    //roll dice with random dice numbers
    public void rollDice(){
        for(Dice dice : playerDices){
            dice.setRandomInt();
        }
    }

    public String toString() {
        return playerName;
    }
}
